version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Ideally, use a more secure password in production
      POSTGRES_DB: document_rag
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db # Use the service name, not localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password # Match the DB password from the db service
      DATABASE_NAME: document_rag # Match the DB name
      JWT_SECRET: your_secret_key # Use a secure secret key
      RABBITMQ_URL: amqp://rabbitmq:5672 # use the service name.
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/usr/src/app/uploads # correct the volume mount path.

volumes:
  db_data: