version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document_rag
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: document_rag
      JWT_SECRET: your_secret_key
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads 
volumes:
  db_data: